//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.31 at 07:59:48 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.prasad.thakur/Order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package thakur.prasad.order;
