package com.thakur.dattaprasad.webserviceclient.com.bharath.ws.trainings;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-04-26T21:53:43.661-04:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://trainings.ws.bharath.com/", name = "customerOrdersPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerOrdersPortType {

    @WebMethod
    @WebResult(name = "getordersresponce", targetNamespace = "http://trainings.ws.bharath.com/", partName = "parameter")
    public Getordersresponce getOrders(
        @WebParam(partName = "parameter", name = "getOrdersRequest", targetNamespace = "http://trainings.ws.bharath.com/")
        GetOrdersreq parameter
    );

    @WebMethod
    @WebResult(name = "createOrdersResponse", targetNamespace = "http://trainings.ws.bharath.com/", partName = "parameter")
    public Createordersres createOrders(
        @WebParam(partName = "parameter", name = "createOrdersrequest", targetNamespace = "http://trainings.ws.bharath.com/")
        CreateOrdersreq parameter
    );
}
